apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: asia-south1-docker.pkg.dev/maximal-reserve-430409-e5/ghactions-demo/demo-gke:{{IMAGE_TAG}}
        ports:
        - containerPort: 80
